### PR TITLE
Add support for 3.12, drop EOL 3.7

### PR DESCRIPTION
**Pull request by Jackenmen**
3.12 untested, we'll see if the tests succeed or if there's more work needed. Dropping 3.7 as well since it's way past EOL.

### CODE REVIEW

**Comment by Jackenmen** [comment]
Looks like it all passes and builds the right wheels! Leaving this as a draft since if you don't get to it within a few days, there are probably going to be version bumps needed for the Python version specified in the setup-python action and cibuildwheel version.

**Comment by saghul** [comment]
Thank you!

**Review by saghul — APPROVED** [review]

**Comment by Jackenmen** [comment]
I'm going to note that you can build wheels with RC versions of Python since they're the point at which there are no more ABI changes being made. So if you do happen to have time to cut a release sooner, you can do so safely with the current state of PR as well.

**Comment by Jackenmen** [comment]
Alright, I updated the PR to use stable Python 3.12 and updated cibuildwheel with the version using 3.12.0 for builds as well.

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Cheers! I'll cut out a release now.

**Pull request merged**
