### PR TITLE
add channel kwargs; tests

### PR DESCRIPTION
**Pull request by wumpus**
Discussion in issue 39

### CODE REVIEW

**Comment by saghul** [comment]
Tests pass, great work!  I left one comment since error checking is missing in one place.  Other than that, can you please squash all your commits into one?

**Comment by wumpus** [comment]
I fixed the last thing, you're correct, I wasn't raising the exception properly.

My attempt to squash a second time was unsuccessful, I'm relatively new to git. Isn't there a "squash and merge" button that you can push?

**Comment by wumpus** [comment]
... and I think I figured out the squash.

**Comment by wumpus** [comment]
This is ready to merge, all squashed.

**Comment by wumpus** [comment]
This has been ready to merge for quite a while... discussed, implemented, squashed.

**Comment by saghul** [comment]
Hey, I'm sorry man this fell through the cracks it no longer applies cleanly. Can you please rebase and squash into a single commit? Thanks, and again, I'm sorry for the huge delay here.

**Comment by saghul** [comment]
Landed in 81e5eb7, thanks!

**Comment by wumpus** [comment]
Thank you!

**Pull request closed without merging**
