### PR TITLE
ffi: new style callbacks

### LINKED ISSUE #118: Is it possible to get rid of ffi.callback() use?
Hello!

Approximately one year ago pycares switched from C backend to cffi backend. Current code utilizes ffi callbacks from native library. There is a problem with `ffi.callback` interface - it requires to allocate memory pages with W+X permissions: https://cffi.readthedocs.io/en/latest/using.html#callbacks-old-style

It causes issues on NetBSD and MacOS, but also I experienced same problem on Linux with daemon running as restricted systemd unit with `MemoryDenyWriteExecute=yes` configuration directive.

Is it possible to refactor pycares to use [extern "Python"](https://cffi.readthedocs.io/en/latest/using.html#id4) in order to get rid of legacy callbacks interface and W+X mempages usage?

### PR DESCRIPTION
**Pull request by Snawoot**
Closes #118 

Refactored ffi callbacks to new `extern "Python"` style in order to avoid use of libffi callbacks and W+X mempages usage.

### CODE REVIEW

**Comment by Snawoot** [comment]
2 checks failed due to networking errors. BTW, when I checked logs of failed jobs there were "unable download log" errors popping up from GH Actions UI, so I think we're good.

**Comment by saghul** [comment]
I reran the tests and it' all clear! Thanks for your contribution!

**Comment by Snawoot** [comment]
Hello!

Could you please make pycares release with this fix soon? Mentioned issue breaks at least following packages (because distro provided version of pycares is newer than 3.0.0 and W+X mempages disabled by systemd):

https://packages.debian.org/bullseye/postfix-mta-sts-resolver
https://packages.debian.org/sid/postfix-mta-sts-resolver
https://packages.ubuntu.com/focal/postfix-mta-sts-resolver

**Comment by saghul** [comment]
Sure thing, I;'ll try to cut a release tonight!

**Comment by saghul** [comment]
pycares 3.1.1 has just been released. Please let me know if it's all good now. Cheers!

**Comment by Snawoot** [comment]
@saghul works just fine, thank you!!!

**Pull request merged**
