### PR TITLE
ci, misc: add support for CPython 3.7

### PR DESCRIPTION
**Pull request by linkmauve**
This adds CPython 3.7 support everywhere needed.

Please make a release shortly after this gets merged, so that other projects can depend on the cp37 binary wheel too.

### CODE REVIEW

**Comment by saghul** [comment]
Hi! Thanks for this! Can you please rebase? I fixed a couple of things (a failing test and AppVeyor itself) so now your PR should be tested properly.

Sure, I can do a release after this PR lands.

**Comment by linkmauve** [comment]
Here, rebased, thanks!

**Comment by saghul** [comment]
Hum, looks like some tweaking is necessary to get 3.7 working on Travis: https://github.com/travis-ci/travis-ci/issues/9815 Can you please take a look?

**Comment by linkmauve** [comment]
Using the change suggested in this issue seems to have broken the entire travis check, and I have no idea how to debug that. :/

**Comment by saghul** [comment]
@linkmauve Makes sense, thanks! I guess we are still covered by AppVeyor, so there is that!

**Comment by linkmauve** [comment]
Now that I think about it, doing a release isn’t useful for this change, you could just publish the new -cp37 wheels to pypi.

**Pull request merged**
