### PR TITLE
TTL support for PTR records

### PR DESCRIPTION
**Pull request by dmeloni-radarservices**
The changes are now storing the TTL field in PTR records.

### CODE REVIEW

**Comment by saghul** [comment]
Great work, thanks! I'll take a look asap!

**Comment by dmeloni-radarservices** [comment]
I'll redo the pull request, I squashed the history a bit and also added another feature

**Comment by saghul** [comment]
You can reopen this and force-push to your branch, that's ok too.

**Comment by dmeloni-radarservices** [comment]
https://github.com/saghul/pycares/pull/49 is a cleaner take on it ;)

**Pull request closed without merging**
